repos:
  - repo: 'git://github.com/pre-commit/pre-commit-hooks'
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: (README\.md)$
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-json
  - repo: 'git://github.com/Lucas-C/pre-commit-hooks'
    rev: v1.1.9
    hooks:
      - id: remove-crlf
  - repo: local
    hooks:
      - id: generate-docs
        name: generate-docs
        entry: npm run docs
        language: system
        pass_filenames: false
